### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by hasifm2010** [rkferreira/nagios#1]
I get python error when i run this plugon...please help me.

**Comment by hasifm2010** [comment]
Can you tell me the role of the user to be used?

**Comment by rkferreira** [comment]
This is probably because script cant access the URL.
I've seen also some issue running on old Centos 5, when negotiating SSL, but its python requests module issue.

I use the user as operator, as far I remember. I can double check.
Tks

**Comment by rkferreira** [comment]
The user has "Operator" role.

**Comment by rkferreira** [comment]
Closed.
